version: "3"

services:

  angular-frontend:
    build: ./front-end
    container_name: angular-ui
    ports:
      - "4200:4200"

  node-tdee:
    build: ./
    container_name: node-api-tdee
    restart: always
    ports:
      - "5000:5000"